# Generated by Django 4.0 on 2023-03-01 23:14

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('message', models.CharField(choices=[('Разрешена', 'Разрешена'), ('Запрещена', 'Запрещена')], default='', max_length=30)),
                ('profiles', models.CharField(choices=[('Открытый', 'Открытый'), ('Закрытый', 'Закрытый')], default='', max_length=30)),
                ('notification', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='', max_length=30)),
                ('joined', models.CharField(choices=[('Да,для всех пользователей', 'Да,для всех пользователей'), ('Да,только для друзей', 'Да,только для друзей'), ('Никому', 'Никому')], default='', max_length=30)),
                ('timezone', models.CharField(choices=[('UTC+1', 'UTC+1'), ('UTC+2', 'UTC+2'), ('UTC+3', 'UTC+')], default='', max_length=30)),
                ('date_of_birth', models.CharField(default='', max_length=30)),
                ('sex', models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], default='', max_length=30)),
                ('image', models.ImageField(blank=True, default='profile1.jpg', null=True, upload_to='')),
                ('type', models.CharField(choices=[('Блиц', 'Блиц'), ('Рапид', 'Рапид'), ('Классика', 'Классика')], default='', max_length=30)),
                ('color', models.CharField(choices=[('Белый', 'Белый'), ('Чёрный', 'Чёрный')], default='', max_length=30)),
                ('username', models.CharField(max_length=25, unique=True, verbose_name='username')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Настройки шахмат',
                'verbose_name_plural': 'Настройки шахмат',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
